### PR TITLE
Sort files in archives

### LINKED ISSUE #129: Sort files in archives
Currently, if an archive contains multiple files, they are shown in a random order. It would be better to get a bit more repeatability by sorting them, as I sometimes try to install something, hit 5, it fails (e.g. the file exists), I retry and now I need to hit 8. Not a big deal, just an easy fix.

### PR DESCRIPTION
**Pull request by Stavrospanakakis**
This commit closes #129. When an archive contains multiple files, they are shown in alphabetical order.

Signed-off-by: Stavros Panakakis [stavrospanakakis@gmail.com](mailto:stavrospanakakis@gmail.com)

### CODE REVIEW

File: pkg/assets/assets.go [hunk 1]
```diff
@@ -194,6 +195,11 @@ func (f *Filter) FilterAssets(repoName string, as []*Asset) (*FilteredAsset, err
 		for _, f := range matches {
 			generic = append(generic, f)
 		}
+
+		sort.SliceStable(generic, func(i, j int) bool {
+			return fmt.Sprint(generic[i]) < fmt.Sprint(generic[j])
```
Comment (marcosnils) [inline pkg/assets/assets.go:200]: nit:
```suggestion
			return generic[i].String() < generic[j].String()
```
